spring:
  datasource:
    url: jdbc:h2:file:/data/cookies
    username: quiz
    password: cookie
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  sql:
    init:
      data-locations: "classpath:game_cookie_data.sql,
                        classpath:session_cookie_data.sql"
      mode: always